language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pycodestyle
script:
  - PYTHONPATH=. pycodestyle --config=./pycodestyle_config .
  - PYTHONPATH=. pytest tests
  - PYTHONPATH=. python -c "from valgrind_parser import ValgrindLogParser"
